test_name: This is a test when running a server using configWithDefaultValues.yaml

stages:
- name: The server should return default values upon requesting /
  request:
    url: http://test-server:8080/
    method: GET
  response:
    status_code: 200
