apiVersion: v1
kind: Service
metadata:
  name: test-server-service
  labels:
    app: test-server
spec:
  type: ClusterIP
  selector:
    app: test-server
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080